// Dicionário de pronúncia: palavra em inglês -> leitura fácil em português
const DICT = {
    "i":"ai","me":"mi","my":"mai","mine":"main","you":"iú","your":"iór","yours":"iórs",
    "he":"rí","him":"rim","his":"riz","she":"xi","her":"rer","hers":"rers",
    "it":"it","its":"its","we":"uí","us":"ás","our":"auer","ours":"auers",
    "they":"dei","them":"dem","their":"deir","theirs":"deirs",
    "who":"rú","whom":"rum","whose":"rúz","myself":"maisséuf","yourself":"iórsséuf",
    "himself":"rimsséuf","herself":"rersséuf","itself":"itsséuf","ourselves":"auersséuvs",
    "themselves":"demsséuvs",

    "am":"ém","is":"iz","are":"ar","was":"uóz","were":"uér","be":"bi","been":"bin","being":"biin",
    "do":"du","does":"dãz","did":"did","done":"dãn",
    "have":"rév","has":"réz","had":"réd","having":"révin",
    "will":"uíl","would":"uúd","can":"kén","could":"kúd","should":"chúd",
    "must":"mãst","may":"mei","might":"mait","shall":"chél",

    "what":"uót","when":"uén","where":"uér","why":"uái","how":"rau","which":"uítch",

    "the":"dê","a":"a","an":"an","and":"end","or":"ór","but":"bãt","if":"if",
    "because":"bicóz","so":"sou","not":"nót","no":"nou","yes":"iés",
    "please":"plíz","thanks":"fénks","thank":"fénk","sorry":"sóri","okay":"okei","ok":"okei",
    "to":"tu","too":"tu","of":"óv","for":"fór","with":"uíf","without":"uidáut",
    "from":"from","by":"bai","at":"ét","on":"on","in":"in","up":"ãp","down":"dáun",
    "out":"aut","about":"abáut","into":"íntu","over":"óuver","under":"ãnder",
    "after":"éfter","before":"bifór","between":"bituín","all":"ól","some":"sãm",
    "any":"éni","many":"méni","much":"mãtch","more":"mór","most":"moust","less":"lés",
    "little":"lítol","few":"fiú","other":"ãder","another":"anãder","each":"itch",
    "every":"évri","everyone":"évriuãn","everything":"évrifin","someone":"sãmuãn",
    "something":"sãmfin","nothing":"nãfin","nobody":"noubadi","anyone":"éniuãn",
    "anything":"énifin","that":"dét","this":"dis","these":"díz","those":"douz",
    "there":"dér","here":"rír","as":"éz","than":"dén","then":"dén","also":"ólsou",
    "just":"djãst","only":"óunli","even":"íven","still":"stil","already":"ólrédi",
    "again":"aguén","back":"bék","away":"auéi","really":"ríli","very":"véri",

    "hi":"hai","hello":"rélou","hey":"rei","bye":"bai","goodbye":"gúdbai",
    "good":"gúd","morning":"mórnin","afternoon":"éftenún","evening":"ívnin","night":"nait",
    "today":"tudei","tomorrow":"tumórou","yesterday":"iésterdei","now":"nau",
    "later":"leiter","soon":"sún","always":"óluueiz","never":"néver",
    "sometimes":"sãmtaimz","often":"ófen",

    "go":"gou","going":"gouin","goes":"gouz","went":"uént","gone":"gón",
    "come":"kãm","coming":"kãmin","comes":"kãms","came":"keim",
    "get":"guét","gets":"guéts","getting":"guétin","got":"gót",
    "make":"meik","makes":"meiks","making":"meikin","made":"meid",
    "take":"teik","takes":"teiks","taking":"teikin","took":"tuk","taken":"teikin",
    "see":"si","sees":"siz","seeing":"siin","saw":"só","seen":"sin",
    "look":"lúk","looking":"lúkin","looks":"lúks","looked":"lúkt",
    "know":"nou","knows":"nouz","knowing":"nouin","knew":"niú","known":"noun",
    "think":"finki","thinks":"finks","thinking":"finkin","thought":"fót",
    "want":"uónt","wants":"uónts","wanted":"uóntid","wanting":"uóntin",
    "need":"níd","needs":"níds","needed":"nídid","needing":"nídin",
    "like":"laik","likes":"laiks","liked":"laikt","liking":"laikin",
    "love":"lãv","loves":"lãvs","loved":"lãvd","loving":"lãvin",
    "say":"sei","says":"séz","saying":"seiin","said":"séd",
    "tell":"tél","tells":"téls","telling":"télin","told":"tould",
    "give":"guiv","gives":"guivs","giving":"guivin","given":"guiven",
    "find":"faind","finds":"fainds","finding":"faindin","found":"faund",
    "feel":"fíl","feels":"fíls","feeling":"fílin","felt":"félt",
    "try":"trai","tries":"traiz","trying":"traiin","tried":"traid",
    "ask":"ésk","asks":"ésks","asking":"éskin","asked":"éskt",
    "work":"uérk","works":"uérks","working":"uérkin","worked":"uérkt",
    "call":"kól","calls":"kóls","calling":"kólin","called":"kóld",
    "use":"iúz","uses":"iúziz","using":"iúzin","used":"iúzd",
    "meet":"mit","meets":"míts","meeting":"mítin","met":"mét",
    "live":"liv","lives":"livs","living":"livin","lived":"livd",
    "stay":"stei","stays":"steiz","staying":"steiin","stayed":"steid",
    "leave":"lív","leaves":"lívs","leaving":"lívin","left":"léft",
    "put":"pút","puts":"púts","putting":"pútin",
    "let":"lét","lets":"léts","letting":"létin",
    "keep":"kíp","keeps":"kíps","keeping":"kípin","kept":"képt",
    "help":"rélp","helps":"rélps","helping":"rélpin","helped":"rélpt",
    "talk":"tók","talks":"tóks","talking":"tókin","talked":"tókt",
    "start":"start","starts":"starts","starting":"startin","started":"startid",
    "stop":"stóp","stops":"stóps","stopping":"stópin","stopped":"stópt",
    "play":"plei","plays":"pleiz","playing":"pleiin","played":"pleid",
    "run":"rãn","runs":"rãns","running":"rãnin","ran":"rén",
    "walk":"uók","walks":"uóks","walking":"uókin","walked":"uókt",
    "eat":"it","eats":"its","eating":"itin","eaten":"íten","ate":"eit",
    "drink":"drink","drinks":"drinks","drinking":"drinkin","drank":"drénk",
    "sleep":"slíp","sleeps":"slíps","sleeping":"slípin","slept":"slépt",
    "read":"ríd","reads":"ríds","reading":"rídin",
    "write":"rait","writes":"raits","writing":"raitin","wrote":"rout","written":"ríten",
    "speak":"spík","speaks":"spíks","speaking":"spíkin","spoke":"spouk",
    "listen":"lísen","listens":"lísens","listening":"lísenin","listened":"lísend",
    "watch":"uótch","watches":"uótchiz","watching":"uótchin","watched":"uótcht",
    "open":"oupen","opens":"oupenz","opening":"oupenin","opened":"oupend",
    "close":"clouz","closes":"clouziz","closing":"clouzin","closed":"clouzd",
    "doing":"duin",

    "name":"neim","time":"taim","day":"dei","year":"íer","people":"pípol",
    "man":"mén","woman":"uúman","child":"tcháild","children":"tchíldren",
    "friend":"frénd","family":"fémili","house":"raus","home":"roum",
    "school":"skúl","food":"fúd","water":"uóter","money":"mãni",
    "thing":"fin","things":"fins","life":"laif","world":"uérld","country":"kãntri",
    "city":"síti","place":"pleis","way":"uei","part":"part","point":"point",
    "problem":"próblem","question":"kuéstchion","story":"stóri","music":"miúzik",
    "movie":"múvi","book":"búk","phone":"foun","car":"kar","door":"dór","room":"rúm",
    "nice":"nais","great":"greit","happy":"répi","sad":"séd","new":"niú","old":"ould",

    "red":"réd","blue":"blú","green":"grín","yellow":"iélou","black":"blék",
    "white":"uáit","orange":"órinj","purple":"pérpol","pink":"pink","brown":"bráun",
    "gray":"gréi","grey":"gréi",

    "one":"uãn","two":"tú","three":"frí","four":"fór","five":"faiv","six":"síks",
    "seven":"séven","eight":"eit","nine":"nain","ten":"ten","eleven":"iléven",
    "twelve":"tuélv","thirteen":"fertín","fourteen":"fortín","fifteen":"fiftín",
    "sixteen":"sikstín","seventeen":"seventín","eighteen":"eitín","nineteen":"naintín",
    "twenty":"tuéni","thirty":"férti","forty":"fórti","fifty":"fífti","sixty":"síksti",
    "seventy":"séventi","eighty":"eiti","ninety":"nainti","hundred":"rãndred",
    "thousand":"fauzend","million":"mílian","zero":"zírou",

    "monday":"mãndei","tuesday":"tiúzdei","wednesday":"uénzdei","thursday":"férzdei",
    "friday":"fraidei","saturday":"séterdei","sunday":"sãndei",

    "big":"big","small":"smól","beautiful":"biútiful","easy":"ízi","hard":"rard",
    "difficult":"díficult","important":"impórtent","different":"díferent",
    "right":"rait","wrong":"róng","true":"trú","sure":"chúr","ready":"rédi",
    "free":"frí","busy":"bízi","tired":"taierd","hungry":"rãngri","thirsty":"férsti",

    "i'm":"aim","i'll":"ail","i've":"aiv","i'd":"aid",
    "you're":"iór","you'll":"iúl","you've":"iúv","you'd":"iúd",
    "he's":"riz","she's":"xiz","it's":"its","we're":"uír","we'll":"uíl","we've":"uív",
    "they're":"deir","they'll":"deil","they've":"deiv",
    "isn't":"ízent","aren't":"árent","wasn't":"uóznt","weren't":"uérent",
    "don't":"dount","doesn't":"dãzent","didn't":"dídent",
    "can't":"ként","couldn't":"kúdent","won't":"uount","wouldn't":"údent",
    "shouldn't":"chúdent","haven't":"révent","hasn't":"rézent","hadn't":"rédent",
    "what's":"uóts","where's":"uérz","who's":"rúz","that's":"déts","there's":"dérz",
    "here's":"rírz","let's":"léts",

    "pizza":"pítza","coffee":"kófi","chocolate":"tchóklit","computer":"kompiúter",
    "internet":"ínternét","hotel":"routél","taxi":"téksi","hamburger":"rémberguer",
    "sandwich":"séndwitch","juice":"djús","beer":"bír","cool":"kúl","awesome":"óssom",
    "welcome":"uélkam","excuse":"ikskiúz","fine":"fain","alright":"ólrait",
    "bathroom":"béfrum","kitchen":"kítchen","street":"strít","airport":"érport",
    "though":"dou","through":"frú","tough":"tãf","enough":"ináf","cough":"kóf",
    "thorough":"férou","bought":"bót","brought":"brót","caught":"kót","taught":"tót",
    "high":"rai","light":"lait","night":"nait","sight":"sait","flight":"fláit",
    "bright":"brait","own":"oun","show":"chou","grow":"grou",
    "throw":"frou","slow":"slou","below":"bilou","window":"uíndou","maybe":"meibi"
};

// Classificação gramatical: palavra -> categoria (verbo, pronome, substantivo...)
const POS_GROUPS = {
    "pronome": ["i","me","my","mine","you","your","yours","he","him","his","she","her","hers",
      "it","its","we","us","our","ours","they","them","their","theirs","myself","yourself",
      "himself","herself","itself","ourselves","themselves","this","that","these","those"],
    "pronome interrogativo": ["who","whom","whose","what","which"],
    "advérbio": ["when","where","why","how","not","so","too","also","just","only","even","still",
      "already","again","back","away","really","very","now","today","tomorrow","yesterday",
      "later","soon","always","never","sometimes","often","here","there","yes","no","maybe"],
    "artigo": ["a","an","the"],
    "conjunção": ["and","or","but","because","if","than","then"],
    "preposição": ["of","for","with","without","from","by","at","on","in","up","down","out",
      "about","into","over","under","after","before","between","to"],
    "interjeição": ["hi","hello","hey","bye","goodbye","please","thanks","thank","sorry","okay",
      "ok","welcome","excuse","awesome","cool"],
    "pronome indefinido": ["all","some","any","many","much","more","most","less","little","few",
      "other","another","each","every","everyone","everything","someone","something","nothing",
      "nobody","anyone","anything"],
    "verbo": ["am","is","are","was","were","be","been","being","do","does","did","done","have",
      "has","had","having","will","would","can","could","should","must","may","might","shall",
      "go","going","goes","went","gone","come","coming","comes","came","get","gets","getting","got",
      "make","makes","making","made","take","takes","taking","took","taken","see","sees","seeing","saw","seen",
      "look","looking","looks","looked","know","knows","knowing","knew","known","think","thinks","thinking","thought",
      "want","wants","wanted","wanting","need","needs","needed","needing","like","likes","liked","liking",
      "love","loves","loved","loving","say","says","saying","said","tell","tells","telling","told",
      "give","gives","giving","given","find","finds","finding","found","feel","feels","feeling","felt",
      "try","tries","trying","tried","ask","asks","asking","asked","work","works","working","worked",
      "call","calls","calling","called","use","uses","using","used","meet","meets","meeting","met",
      "live","lives","living","lived","stay","stays","staying","stayed","leave","leaves","leaving","left",
      "put","puts","putting","let","lets","letting","keep","keeps","keeping","kept","help","helps","helping","helped",
      "talk","talks","talking","talked","start","starts","starting","started","stop","stops","stopping","stopped",
      "play","plays","playing","played","run","runs","running","ran","walk","walks","walking","walked",
      "eat","eats","eating","eaten","ate","drink","drinks","drinking","drank","sleep","sleeps","sleeping","slept",
      "read","reads","reading","write","writes","writing","wrote","written","speak","speaks","speaking","spoke",
      "listen","listens","listening","listened","watch","watches","watching","watched","open","opens","opening","opened",
      "close","closes","closing","closed","doing",
      "i'm","i'll","i've","i'd","you're","you'll","you've","you'd","he's","she's","it's","we're","we'll","we've",
      "they're","they'll","they've","isn't","aren't","wasn't","weren't","don't","doesn't","didn't","can't","couldn't",
      "won't","wouldn't","shouldn't","haven't","hasn't","hadn't","what's","where's","who's","that's","there's",
      "here's","let's","though","bought","brought","caught","taught"],
    "substantivo": ["name","time","day","year","people","man","woman","child","children","friend","family",
      "house","home","school","food","water","money","thing","things","life","world","country","city","place",
      "way","part","point","problem","story","music","movie","book","phone","car","door","room","morning",
      "afternoon","evening","night","monday","tuesday","wednesday","thursday","friday","saturday","sunday",
      "pizza","coffee","chocolate","computer","internet","hotel","taxi","hamburger","sandwich","juice","beer",
      "bathroom","kitchen","street","airport","window","question"],
    "adjetivo": ["nice","great","happy","sad","new","old","big","small","beautiful","easy","hard","difficult",
      "important","different","right","wrong","true","sure","ready","free","busy","tired","hungry","thirsty",
      "good","fine","alright","red","blue","green","yellow","black","white","orange","purple","pink","brown",
      "gray","grey","tough","enough","high","light","bright","own","slow"],
    "numeral": ["one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve",
      "thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen",
      "twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety",
      "hundred","thousand","million","zero"]
};

  const POS = {};
  Object.keys(POS_GROUPS).forEach(cat => {
    POS_GROUPS[cat].forEach(w => { POS[w] = cat; });
  });

// Tradução aproximada para o português (mostrada no pop-up)
const TRANSLATE = {
    "i":"eu","me":"mim / me","my":"meu / minha","mine":"o meu","you":"você / tu",
    "your":"seu / sua","yours":"o seu","he":"ele","him":"ele (objeto)","his":"dele",
    "she":"ela","her":"ela / dela","hers":"o dela","it":"isso / ele(a)","its":"dele(a) (objeto)",
    "we":"nós","us":"nós (objeto)","our":"nosso / nossa","ours":"o nosso","they":"eles / elas",
    "them":"eles / elas (objeto)","their":"deles / delas","theirs":"o deles",
    "who":"quem","whom":"quem (objeto)","whose":"de quem","myself":"eu mesmo",
    "yourself":"você mesmo","himself":"ele mesmo","herself":"ela mesma",
    "itself":"ele mesmo (objeto)","ourselves":"nós mesmos","themselves":"eles mesmos",

    "am":"sou / estou","is":"é / está","are":"são / estão","was":"era / estava",
    "were":"eram / estavam","be":"ser / estar","been":"sido / estado","being":"sendo / estando",
    "do":"fazer","does":"faz","did":"fez","done":"feito","have":"ter","has":"tem",
    "had":"tinha / teve","having":"tendo","will":"vai (futuro)","would":"iria",
    "can":"pode / consegue","could":"poderia","should":"deveria","must":"deve / precisa",
    "may":"pode (permissão)","might":"poderia (talvez)","shall":"vai (formal)",

    "what":"o que / qual","when":"quando","where":"onde","why":"por que","how":"como","which":"qual",

    "the":"o / a","a":"um / uma","an":"um / uma","and":"e","or":"ou","but":"mas","if":"se",
    "because":"porque","so":"então / tão","not":"não","no":"não","yes":"sim","please":"por favor",
    "thanks":"obrigado","thank":"agradecer","sorry":"desculpa","okay":"está bem","ok":"está bem",
    "to":"para / a","too":"também","of":"de","for":"para / por","with":"com","without":"sem",
    "from":"de / desde","by":"por / perto de","at":"em / às","on":"em / sobre","in":"em / dentro de",
    "up":"para cima","down":"para baixo","out":"fora","about":"sobre / cerca de","into":"para dentro de",
    "over":"sobre / acima de","under":"sob / embaixo de","after":"depois de","before":"antes de",
    "between":"entre","all":"tudo / todos","some":"alguns","any":"algum / qualquer","many":"muitos",
    "much":"muito","more":"mais","most":"a maioria","less":"menos","little":"pouco","few":"poucos",
    "other":"outro","another":"mais um","each":"cada","every":"todo / cada","everyone":"todo mundo",
    "everything":"tudo","someone":"alguém","something":"alguma coisa","nothing":"nada",
    "nobody":"ninguém","anyone":"alguém","anything":"qualquer coisa","that":"que / aquele(a)",
    "this":"este / esta","these":"estes / estas","those":"aqueles / aquelas","there":"lá / ali",
    "here":"aqui","as":"como / enquanto","than":"do que","then":"então / depois","also":"também",
    "just":"só / apenas","only":"só / apenas","even":"até (mesmo)","still":"ainda","already":"já",
    "again":"de novo","back":"de volta","away":"para longe","really":"realmente","very":"muito",

    "hi":"oi","hello":"olá","hey":"ei","bye":"tchau","goodbye":"adeus","good":"bom / boa",
    "morning":"manhã","afternoon":"tarde","evening":"noite (início)","night":"noite",
    "today":"hoje","tomorrow":"amanhã","yesterday":"ontem","now":"agora","later":"mais tarde",
    "soon":"em breve","always":"sempre","never":"nunca","sometimes":"às vezes","often":"frequentemente",

    "go":"ir","going":"indo","goes":"vai","went":"foi","gone":"ido","come":"vir","coming":"vindo",
    "comes":"vem","came":"veio","get":"pegar / conseguir","gets":"pega","getting":"pegando","got":"pegou",
    "make":"fazer","makes":"faz","making":"fazendo","made":"fez","take":"pegar / levar","takes":"pega",
    "taking":"pegando","took":"pegou","taken":"pego","see":"ver","sees":"vê","seeing":"vendo",
    "saw":"viu","seen":"visto","look":"olhar","looking":"olhando","looks":"olha / parece","looked":"olhou",
    "know":"saber / conhecer","knows":"sabe","knowing":"sabendo","knew":"sabia","known":"sabido",
    "think":"pensar / achar","thinks":"pensa","thinking":"pensando","thought":"pensou",
    "want":"querer","wants":"quer","wanted":"queria","wanting":"querendo","need":"precisar",
    "needs":"precisa","needed":"precisou","needing":"precisando","like":"gostar","likes":"gosta",
    "liked":"gostou","liking":"gostando","love":"amar","loves":"ama","loved":"amou","loving":"amando",
    "say":"dizer","says":"diz","saying":"dizendo","said":"disse","tell":"contar / dizer","tells":"conta",
    "telling":"contando","told":"contou","give":"dar","gives":"dá","giving":"dando","given":"dado",
    "find":"encontrar","finds":"encontra","finding":"encontrando","found":"encontrou","feel":"sentir",
    "feels":"sente","feeling":"sentindo","felt":"sentiu","try":"tentar","tries":"tenta",
    "trying":"tentando","tried":"tentou","ask":"perguntar / pedir","asks":"pergunta","asking":"perguntando",
    "asked":"perguntou","work":"trabalhar","works":"trabalha","working":"trabalhando","worked":"trabalhou",
    "call":"chamar / ligar","calls":"chama","calling":"chamando","called":"chamou","use":"usar",
    "uses":"usa","using":"usando","used":"usou","meet":"encontrar / conhecer","meets":"encontra",
    "meeting":"encontrando","met":"encontrou","live":"morar / viver","lives":"mora","living":"morando",
    "lived":"morou","stay":"ficar","stays":"fica","staying":"ficando","stayed":"ficou",
    "leave":"sair / deixar","leaves":"sai","leaving":"saindo","left":"saiu","put":"colocar",
    "puts":"coloca","putting":"colocando","let":"deixar / permitir","lets":"deixa","letting":"deixando",
    "keep":"manter / guardar","keeps":"mantém","keeping":"mantendo","kept":"manteve","help":"ajudar",
    "helps":"ajuda","helping":"ajudando","helped":"ajudou","talk":"falar / conversar","talks":"fala",
    "talking":"falando","talked":"falou","start":"começar","starts":"começa","starting":"começando",
    "started":"começou","stop":"parar","stops":"para","stopping":"parando","stopped":"parou",
    "play":"jogar / tocar","plays":"joga","playing":"jogando","played":"jogou","run":"correr",
    "runs":"corre","running":"correndo","ran":"correu","walk":"andar","walks":"anda","walking":"andando",
    "walked":"andou","eat":"comer","eats":"come","eating":"comendo","eaten":"comido","ate":"comeu",
    "drink":"beber","drinks":"bebe","drinking":"bebendo","drank":"bebeu","sleep":"dormir",
    "sleeps":"dorme","sleeping":"dormindo","slept":"dormiu","read":"ler","reads":"lê","reading":"lendo",
    "write":"escrever","writes":"escreve","writing":"escrevendo","wrote":"escreveu","written":"escrito",
    "speak":"falar","speaks":"fala","speaking":"falando","spoke":"falou","listen":"escutar",
    "listens":"escuta","listening":"escutando","listened":"escutou","watch":"assistir","watches":"assiste",
    "watching":"assistindo","watched":"assistiu","open":"abrir","opens":"abre","opening":"abrindo",
    "opened":"abriu","close":"fechar","closes":"fecha","closing":"fechando","closed":"fechou","doing":"fazendo",

    "name":"nome","time":"tempo / hora","day":"dia","year":"ano","people":"pessoas","man":"homem",
    "woman":"mulher","child":"criança","children":"crianças","friend":"amigo","family":"família",
    "house":"casa","home":"lar","school":"escola","food":"comida","water":"água","money":"dinheiro",
    "thing":"coisa","things":"coisas","life":"vida","world":"mundo","country":"país","city":"cidade",
    "place":"lugar","way":"caminho / jeito","part":"parte","point":"ponto","problem":"problema",
    "story":"história","music":"música","movie":"filme","book":"livro","phone":"telefone","car":"carro",
    "door":"porta","room":"quarto / sala","nice":"legal","great":"ótimo","happy":"feliz","sad":"triste",
    "new":"novo","old":"velho",

    "red":"vermelho","blue":"azul","green":"verde","yellow":"amarelo","black":"preto","white":"branco",
    "orange":"laranja","purple":"roxo","pink":"rosa","brown":"marrom","gray":"cinza","grey":"cinza",

    "one":"um","two":"dois","three":"três","four":"quatro","five":"cinco","six":"seis","seven":"sete",
    "eight":"oito","nine":"nove","ten":"dez","eleven":"onze","twelve":"doze",
    "thirteen":"treze","fourteen":"catorze","fifteen":"quinze","sixteen":"dezesseis",
    "seventeen":"dezessete","eighteen":"dezoito","nineteen":"dezenove","twenty":"vinte",
    "thirty":"trinta","forty":"quarenta","fifty":"cinquenta","sixty":"sessenta",
    "seventy":"setenta","eighty":"oitenta","ninety":"noventa","hundred":"cem","thousand":"mil",
    "million":"milhão","zero":"zero",

    "monday":"segunda-feira","tuesday":"terça-feira","wednesday":"quarta-feira","thursday":"quinta-feira",
    "friday":"sexta-feira","saturday":"sábado","sunday":"domingo",

    "big":"grande","small":"pequeno","beautiful":"bonito","easy":"fácil","hard":"difícil / duro",
    "difficult":"difícil","important":"importante","different":"diferente","right":"certo",
    "wrong":"errado","true":"verdadeiro","sure":"certeza","ready":"pronto","free":"livre / grátis",
    "busy":"ocupado","tired":"cansado","hungry":"com fome","thirsty":"com sede",

    "i'm":"eu sou / estou","i'll":"eu vou","i've":"eu tenho / já","i'd":"eu iria / tinha",
    "you're":"você é / está","you'll":"você vai","you've":"você tem","you'd":"você iria",
    "he's":"ele é / está","she's":"ela é / está","it's":"é / está (isso)","we're":"nós somos / estamos",
    "we'll":"nós vamos","we've":"nós temos","they're":"eles são / estão","they'll":"eles vão",
    "they've":"eles têm","isn't":"não é","aren't":"não são","wasn't":"não era","weren't":"não eram",
    "don't":"não (faz)","doesn't":"não (faz)","didn't":"não fez","can't":"não pode","couldn't":"não podia",
    "won't":"não vai","wouldn't":"não iria","shouldn't":"não deveria","haven't":"não tenho",
    "hasn't":"não tem","hadn't":"não tinha","what's":"o que é","where's":"onde está","who's":"quem é",
    "that's":"isso é","there's":"há / tem","here's":"aqui está","let's":"vamos",

    "pizza":"pizza","coffee":"café","chocolate":"chocolate","computer":"computador","internet":"internet",
    "hotel":"hotel","taxi":"táxi","hamburger":"hambúrguer","sandwich":"sanduíche","juice":"suco",
    "beer":"cerveja","cool":"legal","awesome":"incrível","welcome":"bem-vindo","excuse":"desculpa / licença",
    "fine":"bem / ótimo","alright":"tudo bem","bathroom":"banheiro","kitchen":"cozinha","street":"rua",
    "airport":"aeroporto","though":"mas / apesar disso","through":"através de","tough":"difícil / duro",
    "enough":"suficiente","cough":"tosse","thorough":"minucioso","bought":"comprou","brought":"trouxe",
    "caught":"pegou","taught":"ensinou","high":"alto","light":"luz / leve","sight":"visão","flight":"voo",
    "bright":"brilhante","own":"próprio","show":"mostrar","grow":"crescer","throw":"jogar / lançar",
    "slow":"lento","below":"abaixo","window":"janela","question":"pergunta","maybe":"talvez"
};

// Números por extenso (inglês e português)
  const EN_ONES = ["zero","one","two","three","four","five","six","seven","eight","nine"];
  const EN_TEENS = ["ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen"];
  const EN_TENS = ["","","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety"];

  const PT_ONES = ["zero","um","dois","três","quatro","cinco","seis","sete","oito","nove"];
  const PT_TEENS = ["dez","onze","doze","treze","catorze","quinze","dezesseis","dezessete","dezoito","dezenove"];
  const PT_TENS = ["","","vinte","trinta","quarenta","cinquenta","sessenta","setenta","oitenta","noventa"];
  const PT_HUNDREDS = ["","cento","duzentos","trezentos","quatrocentos","quinhentos","seiscentos","setecentos","oitocentos","novecentos"];

// Nomes próprios comuns em inglês, com a pronúncia certa
const NAMES = {
    "michael":"máikou","john":"djón","james":"djeims","robert":"róbert","david":"déivid",
    "william":"uíliam","richard":"rítchard","joseph":"djóusef","thomas":"tómas","charles":"tcharls",
    "christopher":"krístofer","daniel":"dêniou","matthew":"mátiu","anthony":"ântoni","mark":"mark",
    "donald":"dónald","steven":"stíven","stephen":"stíven","paul":"pól","andrew":"êndru",
    "joshua":"djóchua","kenneth":"kênet","kevin":"kévin","brian":"braien","george":"djórdj",
    "edward":"édward","ronald":"rónald","timothy":"tímoti","jason":"djeisen","jeffrey":"djéfri",
    "ryan":"raien","jacob":"djeikob","gary":"guéri","nicholas":"níkolas","eric":"érik",
    "jonathan":"djónaten","larry":"léri","justin":"djástin","scott":"skót","brandon":"brêndon",
    "benjamin":"bêndjamin","samuel":"sámiuel","gregory":"grégori","frank":"frênk","raymond":"réimond",
    "alexander":"aléksânder","patrick":"pátrik","jack":"djék","dennis":"dênis","jerry":"djéri",
    "tyler":"táiler","aaron":"éron","henry":"rênri","adam":"ádam","douglas":"dáglas",
    "nathan":"néiten","peter":"píter","zachary":"zákari","walter":"uólter","kyle":"káiou",
    "harold":"rárold","carl":"karl","arthur":"ártur","gerald":"djérald","roger":"ródjer",
    "keith":"kít","jeremy":"djérami","terry":"téri","lawrence":"lórens","sean":"chón",
    "christian":"krístian","ethan":"íten","austin":"óstin","jesse":"djési","bruce":"brus",
    "ralph":"rálf","roy":"rói","eugene":"iudjín","louis":"lúis","philip":"fílip",
    "bobby":"bóbi","johnny":"djóni","wayne":"uéin","billy":"bíli","albert":"álbert",
    "fred":"fréd","leonard":"lénard","todd":"tód","craig":"kréig","alan":"álan",
    "randy":"rêndi","victor":"víktor","russell":"rássel","vincent":"vínsent","lucas":"lúkas",
    "owen":"óuen","noah":"nóua","oliver":"óliver","logan":"lóugan","carter":"kárter",
    "wyatt":"uáiat","luke":"luk","isaac":"áizek","connor":"kóner","dylan":"dílan",

    "mary":"méri","patricia":"patríxa","jennifer":"djênifer","linda":"línda","elizabeth":"elízabet",
    "barbara":"bárbara","susan":"súzan","jessica":"djéssika","sarah":"sséra","karen":"kéren",
    "nancy":"nênsi","lisa":"líza","margaret":"márgaret","betty":"béti","sandra":"sêndra",
    "ashley":"áchli","kimberly":"kímberli","emily":"êmili","donna":"dóna","michelle":"michél",
    "carol":"károu","amanda":"amênda","melissa":"melíssa","deborah":"débora","stephanie":"stéfani",
    "rebecca":"rebéka","laura":"lóra","sharon":"chéren","cynthia":"síntia","kathleen":"kátlin",
    "amy":"êimi","angela":"êndjela","shirley":"chérli","anna":"âna","ruth":"rut",
    "brenda":"brênda","pamela":"pámela","nicole":"nikól","katherine":"kátrin","samantha":"samênta",
    "christine":"krístin","emma":"êma","catherine":"kátrin","debra":"débra","virginia":"verdjínia",
    "rachel":"réitchou","carolyn":"károlin","janet":"djênet","heather":"rêder","diane":"daién",
    "julie":"djúli","joyce":"djóis","victoria":"viktória","kelly":"kéli","christina":"kristína",
    "joan":"djóun","evelyn":"évelin","judith":"djúdit","megan":"mégan","andrea":"êndria",
    "cheryl":"chérou","hannah":"rêna","jacqueline":"djákelin","martha":"márta","gloria":"glória",
    "teresa":"teréza","ann":"én","sara":"sséra","madison":"mádisen","frances":"frênses",
    "kathryn":"kátrin","janice":"djênis","jean":"djín","abigail":"ábigueiou","alice":"élis",
    "julia":"djúlia","judy":"djúdi","sophia":"soufía","grace":"gréis","denise":"deníz",
    "amber":"âmber","doris":"dóris","marilyn":"mérilin","danielle":"daniéu","beverly":"béverli",
    "isabella":"izabéla","diana":"daiêna","natalie":"nátali","brittany":"brítani",
    "charlotte":"chárlot","kayla":"kéila","alexis":"aléksis","lori":"lóri","olivia":"olívia",
    "zoe":"zóui","chloe":"clóui","hailey":"réili","mia":"máia",

    "smith":"ssmít","johnson":"djônsen","williams":"uíliams","brown":"bráun","jones":"djóuns",
    "garcia":"garssía","miller":"míler","davis":"déivis","wilson":"uílsen","anderson":"ênderssen",
    "taylor":"téiler","moore":"múr","jackson":"djáksen","martin":"mártin","lee":"li",
    "thompson":"támpsen","white":"uáit","harris":"rárris","clark":"klark","lewis":"lúis",
    "walker":"uóker","young":"iâng","king":"king","wright":"rait","green":"grín",
    "baker":"béiker","adams":"ádams","nelson":"nélsen","carter":"kárter","mitchell":"mítchou",
    "roberts":"róberts","turner":"térner","phillips":"fílips","campbell":"kêmbou","parker":"párker",
    "evans":"évans","edwards":"édwards","collins":"kólins","stewart":"stiuart","morris":"mórris",
    "rogers":"ródjers","cook":"kuk","morgan":"mórgan","bell":"béu","murphy":"mérfi",
    "bailey":"béili","cooper":"kúper","howard":"ráuard","ward":"uórd","gray":"gréi",
    "watson":"uótssen","brooks":"bruks","sanders":"sênders","price":"prais","bennett":"bênet",
    "wood":"úd","barnes":"barns","ross":"róss","henderson":"rênderssen","foster":"fóster",
    "butler":"bâtler","russell":"rássel","griffin":"grífin","hayes":"reis"
};

// Lista de cores para o guia rápido (palavra em inglês + amostra de cor)
const COLORS = [
  { en: "red", hex: "#e5484d" },
  { en: "orange", hex: "#f76b15" },
  { en: "yellow", hex: "#f5d90a" },
  { en: "green", hex: "#30a46c" },
  { en: "blue", hex: "#0091ff" },
  { en: "purple", hex: "#8e4ec6" },
  { en: "pink", hex: "#e93d82" },
  { en: "brown", hex: "#a1694f" },
  { en: "gray", hex: "#8b8d98" },
  { en: "black", hex: "#1a1a1a" },
  { en: "white", hex: "#ffffff" }
];
